[workspace]
resolver = "2"

members = [
    "groups_server",
    "groups_core",
    "groups_server_local"
]

[profile.release]
debug = true
overflow-checks = true
split-debuginfo = "packed"

[profile.dev]
split-debuginfo = "packed"
