[package]
name = "groups_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-rocket = "0.18"
shuttle-runtime = "0.18"
rocket = { version = "0.5.0-rc.3" }
tokio = "1"
